
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityalibou
    username: root
    password: SLAMA250@@mahmoud##
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Utilisez "update" au lieu de "create-drop"

    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        format_sql: true
    database: mysql
application :
  security:
    jwt:
      secret-key : 3e58950f9b875dddf66b25bd1b846e78c8c2bb923ee8cbd7f72695aefb626be3
      expiration : 86400000
      refresh-token :
        expiration : 604800000